version: '3.8'

services:
  dev:
    container_name: monex-core-service
    image: thinhlt/monex-core-service
    build:
      context: .
      target: development
      #      target: production
      dockerfile: ./Dockerfile
    #    command: npm run start:debug
    #    command: -c 'tail -f /dev/null'
    #    entrypoint: /bin/sh
    #    command: npx nest start
    ports:
      - 8004:8004
    #    volumes:
    #      - .:/usr/src/app
    #      - /usr/src/app/node_modules
    restart: unless-stopped
    environment:
      - SERVER_TIMEOUT=1080000
      - SERVER_PORT=8004
      - HTTP_TIMEOUT=5000
      - HTTP_MAX_REDIRECTS=5
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=dance_studio
      - DATABASE_TYPE=mysql
      - DATABASE_CONNECTION_TIME_OUT=15000
      - DATABASE_ACQUIRE_TIME_OUT=15000
      - DATABASE_CONNECTION_LIMIT=20
      - JWT_SECRET=sm56FNVF53gYfCar
networks:
  nesjs-network:
